#include <stdio.h>
#include <stdlib.h>

void *calloc(size_t nmemb, size_t size);
void exit(int status);

/* generated by myy.scm */

int heap[] = {2, 2, 94, 2, 94, 12, 38, 2, 102, 28, 94, 36, 20, 44, 110, 52, 614, 60, 22, 68, 94, 76, 14, 84, 94, 92, 38, 2, 108, 2, 2, 116, 2, 124, 132, 2, 100, 140, 3};

#define CELLS 10000
#define allocp(val) (0==(((int)val)&2))
#define immediatep(val) (2==(((int)val)&2))
#define imm(type,payload) (2 | (type << 3) | (payload << 8))
#define fixval(n) (((int) n) >> 3)
#define fixnum(n) (((int) n) << 3) | 6)
#define fixnump(n) ((((int) n) & 7) == 6)
#define MNULL imm(0, 0)
#define MTRUE imm(1, 1)
#define MFALSE imm(1, 0)
#define aof(inst) ((inst >> 6) & 255)
#define bof(inst) (inst >> 14)
#define car(ptr) *((int *) (((int) ptr) & ~4))
#define cdr(ptr) *((int *) (4 | ((int) ptr)))
#define cons(a, b) (pair((int) a, (int) b)|4)

int S, E, C, D;
int *start, *fp, *end;

int pair(int a, int b) {
   int *this = fp;
   if ((int)fp == MNULL) {
      printf("GC time\n");
      exit(1);
   }
   fp += 2;
   this[0] = a;
   this[1] = b;
   return (int) this;
}

int lref(int lst, int pos) {
   while(pos--)
      lst = cdr(lst);
   return car(lst);
}

int run() {
   while (C != MNULL) {
      int inst = fixval(car(C));
      C = cdr(C);
      switch(inst&63) {
         printf("inst %d\n", inst&63);
         case 11: /* op-load-value */
            printf("load-value if fixnum %d\n", fixval(car(C)));
            S = cons(car(C), S);
            C = cdr(C);
            break;
         case 12: /* op-equal */
            printf("comparing poss %d and %d -> %s\n", aof(inst), bof(inst), ((lref(S, aof(inst)) == lref(S, bof(inst))) ? "true" : "false"));
            S = cons(((lref(S, aof(inst)) == lref(S, bof(inst))) ? MTRUE : MFALSE), S);
            break;
         case 13: { /* op-if */
            C = ((lref(S, aof(inst)) == MFALSE) ? cdr(C) : car(C));
            break; }
         case 3: 
            printf("Loading pos %d from stack\n", aof(inst));
            S = cons(lref(S, aof(inst)), S);
            break;
         case 4: { /* op-return */
            int rval = car(S);
            int st = car(D);
            D = cdr(D);
            S = car(st); st = cdr(st);
            E = car(st); st = cdr(st);
            C = car(st);
            S = cons(rval, S);
            if ((int) D == MNULL) {
               if (fixnump(car(S))) {
                  printf("VM HALT fixnum %d\n", fixval(car(S)));
               } else {
                  printf("VM HALT %d\n", car(S));
               }
               return fixval(car(S));
            }
            break;
         }
         default:
            printf("vm: what inst is %d\n", inst&63);
            return 1;
      }
   }
   printf("C is null, what now?\n");
   return 1;
}

void load_heap() {
   int pos = 0;
   int *hp = start;
   int val;
   while (1) {
      int val = heap[pos];
      if (val == 3) { break; }
      *hp = (immediatep(val) ? val : ((int) start) + val);
      hp++;
      pos++;     
   }
   fp = hp;
   while(fp < end) { /* first sweep */
      cdr(fp) = ((int)fp)+8;
      fp++;
      fp++;
   }
   fp -= 2;
   cdr(fp) = MNULL;
   hp -= 2; /* last loaded is (C . E) */
   S = MNULL;
   E = MNULL;
   C = hp[0];
   D = hp[1];
}

int main(int nargs, char **args) {
   start  = (int *) calloc((sizeof (int *)), 2 * CELLS);
   end = ((int *) start) + 2*CELLS;
   load_heap();   
   return run();
}
